// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Flomz-vrrOQhF24XbTOmV6cL8dmjhk8',
    appId: '1:990524283046:web:aadbed8ef8aa85f7c53c67',
    messagingSenderId: '990524283046',
    projectId: 'publicgovpro-4e5bf',
    authDomain: 'publicgovpro-4e5bf.firebaseapp.com',
    storageBucket: 'publicgovpro-4e5bf.appspot.com',
    measurementId: 'G-22S8QHE85B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNLGhn7dBIgjB9yC63yJuB8jzxUU9lteA',
    appId: '1:990524283046:android:a17632f45e208d94c53c67',
    messagingSenderId: '990524283046',
    projectId: 'publicgovpro-4e5bf',
    storageBucket: 'publicgovpro-4e5bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNN4PGgqG2xtpKrKx5S_5csCO9UrPQbWo',
    appId: '1:990524283046:ios:dbec3b33b35cce59c53c67',
    messagingSenderId: '990524283046',
    projectId: 'publicgovpro-4e5bf',
    storageBucket: 'publicgovpro-4e5bf.appspot.com',
    iosBundleId: 'com.example.publicgovpr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNN4PGgqG2xtpKrKx5S_5csCO9UrPQbWo',
    appId: '1:990524283046:ios:569480fa5bf5f995c53c67',
    messagingSenderId: '990524283046',
    projectId: 'publicgovpro-4e5bf',
    storageBucket: 'publicgovpro-4e5bf.appspot.com',
    iosBundleId: 'com.example.publicgovpr.RunnerTests',
  );
}
